CREATE DATABASE IF NOT EXISTS DB_INVENTORY CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS T_INVENTORY;

CREATE TABLE IF NOT EXISTS T_INVENTORY(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	gewicht FLOAT NOT NULL,
	beschreibung VARCHAR(255) NOT NULL,
	standort VARCHAR(255) NOT NULL,
	raum VARCHAR(255) NOT NULL,
	typ VARCHAR(255) NOT NULL,
	addedDateTime TIMESTAMP NOT NULL,
	addedBy VARCHAR(255),
	lastServiceDateTime TIMESTAMP NULL,
	lastServiceBy VARCHAR(255),
	nextServiceDataTime TIMESTAMP NULL,
	PRIMARY KEY (id),
	UNIQUE (name)
)


