CREATE DATABASE IF NOT EXISTS DB_INVENTORY CHARACTER SET utf8 COLLATE utf8_general_ci;
USE DB_INVENTORY;
DROP TABLE IF EXISTS T_INVENTORY;

CREATE TABLE IF NOT EXISTS T_INVENTORY(
	id INT NOT NULL AUTO_INCREMENT,
	item_name VARCHAR(255) NOT NULL,
	weight FLOAT NOT NULL,
	description VARCHAR(255) NOT NULL,
	location VARCHAR(255) NOT NULL,
	room VARCHAR(255) NOT NULL,
	item_type VARCHAR(255) NOT NULL,
	added_datetime TIMESTAMP NOT NULL,
	added_by VARCHAR(255),
	last_service_datetime TIMESTAMP NULL,
	last_service_by VARCHAR(255),
	next_service_datetime TIMESTAMP NULL,
	PRIMARY KEY (id),
	UNIQUE (item_name)
);


